configMap:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "roboshop-dev.cgn2emkia7of.us-east-1.rds.amazonaws.com"
deployment:
  replicas: 1
  imageName: "annurukulasekhar/shipping"
  imageVersion: "1.4.0"
horizontalPodAutoScaler:
  minReplicas: 1
  maxReplicas: 10
  averageUtilization: 20